/**
 * Full rider registration draft — UI only until API exists.
 * File fields store selected file name for display (not uploaded yet).
 */

export type RiderFormState = {
  // Identity & legal person
  legalFullName: string
  preferredDisplayName: string
  dateOfBirth: string
  gender: string
  nationality: string
  nationalIdNumber: string
  idDocumentType: string
  idIssueDate: string
  idExpiryDate: string
  idPhotoFrontName: string
  idPhotoBackName: string
  selfiePhotoName: string
  maritalStatus: string
  langKinyarwanda: boolean
  langEnglish: boolean
  langFrench: boolean
  // Contact & emergency
  primaryMobile: string
  secondaryMobile: string
  whatsappNumber: string
  email: string
  emergencyContactName: string
  emergencyRelationship: string
  emergencyPhone: string
  emergencyAddress: string
  // Account & security
  password: string
  pinOptional: string
  twoFactorPreference: string
  recoveryEmail: string
  recoveryPhone: string
  // Address & geography
  residentialProvince: string
  residentialDistrict: string
  residentialSector: string
  residentialCell: string
  residentialVillage: string
  residentialStreet: string
  residentialLandmark: string
  mailingSameAsResidential: boolean
  mailingAddress: string
  gpsLat: string
  gpsLng: string
  mapPinLabel: string
  deliveryZones: string
  areasRefuse: string
  crossDistrictWilling: string
  crossDistrictWhich: string
  // Vehicle & equipment
  deliveryMode: string
  vehicleCategory: string
  vehicleMake: string
  vehicleModel: string
  vehicleYear: string
  vehicleColor: string
  plateNumber: string
  vehicleRegDocNumber: string
  vehicleRegExpiry: string
  vehiclePhotoFrontName: string
  vehiclePhotoSideName: string
  vehiclePhotoPlateName: string
  engineCc: string
  fuelType: string
  helmetOwned: string
  helmetPhotoName: string
  reflectiveVest: string
  phoneMount: string
  thermalBag: string
  odometer: string
  // Licenses & permits
  drivingLicenseNumber: string
  drivingLicenseClass: string
  drivingLicenseIssue: string
  drivingLicenseExpiry: string
  licensePhotoFrontName: string
  licensePhotoBackName: string
  motoTaxiPermit: string
  municipalPermitNumber: string
  insuranceProvider: string
  insurancePolicyNumber: string
  insuranceCoverageType: string
  insuranceExpiry: string
  insuranceDocName: string
  roadworthinessSticker: string
  // Financial & payouts
  payoutMethod: string
  mtnMomo: string
  mtnMomoNameOnAccount: string
  airtelMoney: string
  bankName: string
  bankBranch: string
  bankAccountName: string
  bankAccountNumber: string
  bankIbanSwift: string
  mobileMoneyRegisteredName: string
  taxIdTin: string
  withholdingVatStatus: string
  currencyPreference: string
  payoutFrequency: string
  // Work & availability
  availabilityType: string
  workMon: boolean
  workTue: boolean
  workWed: boolean
  workThu: boolean
  workFri: boolean
  workSat: boolean
  workSun: boolean
  timeMorning: boolean
  timeLunch: boolean
  timeEvening: boolean
  timeNight: boolean
  maxHoursPerDay: string
  maxHoursPerWeek: string
  noticePeriodMinutes: string
  willingHolidays: string
  shiftNotes: string
  // Capacity & service rules
  maxConcurrentOrders: string
  maxDistanceKm: string
  maxRadiusKm: string
  maxWeightKg: string
  maxVolume: string
  cashOnDeliveryWilling: string
  cashOnDeliveryLimit: string
  coldChainPharma: string
  coldChainTraining: string
  largeCashHandling: string
  // Compliance, safety, background
  backgroundCheckConsent: string
  backgroundCheckConsentDate: string
  backgroundCheckStatus: string
  backgroundCheckRefId: string
  backgroundCheckExpiry: string
  roadSafetyTraining: string
  roadSafetyCertificateName: string
  foodHygieneTraining: string
}

export const initialRiderFormState = (): RiderFormState => ({
  legalFullName: "",
  preferredDisplayName: "",
  dateOfBirth: "",
  gender: "",
  nationality: "",
  nationalIdNumber: "",
  idDocumentType: "",
  idIssueDate: "",
  idExpiryDate: "",
  idPhotoFrontName: "",
  idPhotoBackName: "",
  selfiePhotoName: "",
  maritalStatus: "",
  langKinyarwanda: true,
  langEnglish: false,
  langFrench: false,
  primaryMobile: "",
  secondaryMobile: "",
  whatsappNumber: "",
  email: "",
  emergencyContactName: "",
  emergencyRelationship: "",
  emergencyPhone: "",
  emergencyAddress: "",
  password: "",
  pinOptional: "",
  twoFactorPreference: "",
  recoveryEmail: "",
  recoveryPhone: "",
  residentialProvince: "",
  residentialDistrict: "",
  residentialSector: "",
  residentialCell: "",
  residentialVillage: "",
  residentialStreet: "",
  residentialLandmark: "",
  mailingSameAsResidential: true,
  mailingAddress: "",
  gpsLat: "",
  gpsLng: "",
  mapPinLabel: "",
  deliveryZones: "",
  areasRefuse: "",
  crossDistrictWilling: "",
  crossDistrictWhich: "",
  deliveryMode: "",
  vehicleCategory: "",
  vehicleMake: "",
  vehicleModel: "",
  vehicleYear: "",
  vehicleColor: "",
  plateNumber: "",
  vehicleRegDocNumber: "",
  vehicleRegExpiry: "",
  vehiclePhotoFrontName: "",
  vehiclePhotoSideName: "",
  vehiclePhotoPlateName: "",
  engineCc: "",
  fuelType: "",
  helmetOwned: "",
  helmetPhotoName: "",
  reflectiveVest: "",
  phoneMount: "",
  thermalBag: "",
  odometer: "",
  drivingLicenseNumber: "",
  drivingLicenseClass: "",
  drivingLicenseIssue: "",
  drivingLicenseExpiry: "",
  licensePhotoFrontName: "",
  licensePhotoBackName: "",
  motoTaxiPermit: "",
  municipalPermitNumber: "",
  insuranceProvider: "",
  insurancePolicyNumber: "",
  insuranceCoverageType: "",
  insuranceExpiry: "",
  insuranceDocName: "",
  roadworthinessSticker: "",
  payoutMethod: "",
  mtnMomo: "",
  mtnMomoNameOnAccount: "",
  airtelMoney: "",
  bankName: "",
  bankBranch: "",
  bankAccountName: "",
  bankAccountNumber: "",
  bankIbanSwift: "",
  mobileMoneyRegisteredName: "",
  taxIdTin: "",
  withholdingVatStatus: "",
  currencyPreference: "RWF",
  payoutFrequency: "",
  availabilityType: "",
  workMon: true,
  workTue: true,
  workWed: true,
  workThu: true,
  workFri: true,
  workSat: false,
  workSun: false,
  timeMorning: true,
  timeLunch: true,
  timeEvening: true,
  timeNight: false,
  maxHoursPerDay: "",
  maxHoursPerWeek: "",
  noticePeriodMinutes: "",
  willingHolidays: "",
  shiftNotes: "",
  maxConcurrentOrders: "",
  maxDistanceKm: "",
  maxRadiusKm: "",
  maxWeightKg: "",
  maxVolume: "",
  cashOnDeliveryWilling: "",
  cashOnDeliveryLimit: "",
  coldChainPharma: "",
  coldChainTraining: "",
  largeCashHandling: "",
  backgroundCheckConsent: "",
  backgroundCheckConsentDate: "",
  backgroundCheckStatus: "",
  backgroundCheckRefId: "",
  backgroundCheckExpiry: "",
  roadSafetyTraining: "",
  roadSafetyCertificateName: "",
  foodHygieneTraining: "",
})

/** TODO: replace with real check when product defines required keys. */
export function riderFormCanSave(_form: RiderFormState): boolean {
  return false
}
